### ISSUE TITLE
[Feature Request] Add WHMCS leads to Intercom

### ISSUE THREAD

**Issue by infinitnet** [goodbytes-gb/Intercom-WHMCS-Module#3]
This probably isn't easy to add, but it would be very useful if your module could add the email addresses of unregistered users that open tickets in WHMCS as leads in Intercom. What I mean is a situation like this:

1.) Someone sends an email to sales@company.com, asking about its products. This opens a sales ticket in WHMCS and of course that "someone" isn't a registered user.

2.) Now your module would detect that a new ticket from an unregistered email address has been opened in WHMCS and would add that email as a lead to Intercom, to make it possible to follow-up later on (email sales funnel etc.)

3.) ???

4.) Profit.

**Comment by mforcer** [comment]
This should be possible with the TicketOpen action hook... thanks for the suggestion will test it asap.

**Comment by mforcer** [comment]
After further inspection it looks like this is a little more difficult than first thought. It is indeed possible with the TicketOpen action hook in WHMCS but it would require interacting with the Intercom API. 

Something this addon currently cannot do. 

It would depend on the Intercom PHP SDK API.

This addon essentially requires the user to visit the website. If a visitor opened a ticket via the website, rather than email.. that would be much easier.

We'll close this for now as we do not anticipate adding it anytime soon.
